sample_rate: 24000
# Audio preprocess setting.
highpass_cutoff: 70 # Cut-off-frequency for low-cut-filter.
top_db: 40

# Mel-spectrogram extraction setting.
n_mels: 80
n_fft: 1024
hop_length: 256
win_size: 1024
fmin: 0 # Minimum spectrogram frequency
fmax: 8000
compression: true # Dynamic range compression
clip_val: 1e-5

# Mel-spectrogram extraction setting
mcep_dim: 35

# F0 extraction settings
# hop size is the same as hop_length
# Available F0 Extractor is
# non-nn-f0-extractor: parselmouth, dio, harvest
# nn-f0-extractor: crepe, rmvpe, fcpe,
f0_extractor: harvest
f0_min: 71.0 # Minimum F0 value.
f0_max: 1000 # Maximum F0 value.
threshold: 0.6
fix_by_reaper: true # This is only use with non-nn-f0-extractor

# Formant extraction (burg method) setting
# hop size is the same as hop_length
search_fo_min: 3500
search_fo_max: 6000
search_step: 50 # Hz
fo_win_size: 600 # 0.025 ms
pre_enphasis: 50
