# @package _global_

defaults:
  - _self_
  - model: neuralformants
  - vocoder: hifigan
  - data: jvs

hydra:
  run:
    dir: ./
  output_subdir: null
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s][%(module)s | %(lineno)s] %(message)s"
    disable_existing_loggers: false

out_dir: # Directory to output decoding results.
spkidx: -2
checkpoint_path: # Path to the checkpoint of pre-trained model.
checkpoint_steps: # Path to the checkpoint of pre-trained model.
vocoder_checkpoint_path: exp/jvs.hifigan/checkpoints/checkpoint-400000steps.pkl
seed: 100 # Seed number for random numbers.
save_source: false # Whether to save source excitation signals.
f0_factors: [0.5, 1.0, 1.5] # F0 factor.
# formant_factors: [[1.0, 1.0, 1.0, 1.0], [1.5, 1.5, 1.0, 1.0]] # Formant factor
formants_factors: [
    [1.0, 1.0, 1.0, 1.0],
    [1.5, 1.5, 1.0, 1.0],
    [0.5, 0.5, 1.0, 1.0],
    [1.0, 1.0, 1.5, 1.5],
    [1.0, 1.0, 0.5, 0.5],
  ] # Formant factor
