# @package _global_

defaults:
  - _self_
  - generator: e2enf

hydra:
  run:
    dir: ./
  output_subdir: null
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s][%(module)s | %(lineno)s] %(message)s"
    disable_existing_loggers: false

in_dir: # Path to directory which include wav files you want to process.
out_dir: # Path to directory to save the synthesized wavs.
stats: # Path to statistics file.
checkpoint_path: # Path to pre-trained model.
f0_factors: [1.00] # F0 scaling factor.
formants_factors:
  - [1.0, 1.0, 1.0, 1.0]
seed: 100 # Seed number for random numbers.

# The same paramates should be set as in the training.
sample_rate: 24000 # Sampling rate.
aux_feats:
  ["uv", "lcf0", "cf1", "cf2", "cf3", "cf4", "slope", "centroid", "energy"]
dense_factors: [0.5, 1, 4, 8] # Dense factor in PDCNNs.
df_f0_type: "cf0" # F0 type for dilation factor ("f0" or "cf0").
sine_amp: 0.1 # Sine amplitude.
noise_amp: 0.003 # Noise amplitude.
sine_f0_type: "cf0" # F0 type for sine signal ("f0" or "cf0").
signal_types: ["sine"] # List of input signal types.

# Audio preprocess setting.
highpass_cutoff: 70 # Cut-off-frequency for low-cut-filter.
center: false # Pad the extracted sample to the center of the frame

# Mel-spectrogram extraction setting.
n_mels: 80
hop_length: 300 # Hop size.
win_size: 1200 # Window length.
n_fft: 2048
window: hann # Window function.
fmin: 80 # Minimum frequency in mel basis calculation.
fmax: 7600 # Maximum frequency in mel basis calculation.
clip_val: 1e-5
log: "log10"

# Praat settings
# Use fft_size or win_length of Mel-spectrogram extraction setting
minf0: 75.0 # Minimum F0 value.
maxf0: 600 # Maximum F0 value.
thresholds: 0.6

# Burg
n_formant: 5
fo_max: 5000
fo_win_size: 600
pre_enphasis: 50

device: cuda
