# @package _global_

hydra:
  run:
    dir: ./
  output_subdir: null
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s][%(module)s | %(lineno)s] %(message)s"
    disable_existing_loggers: false

file_list: data/scp/jsut.scp # List filr of input wav files.
out_dir: data/hdf5 # Directory to save generated samples.
feature_format: .h5 # Feature format.
n_jobs: -1

sample_rate: 24000 # Sampling rate.
spkinfo: data/spk_info.yaml # YAML format speaker information.
spkidx: -4 # Speaker index of the split path.
inv: true # If false, wav is restored from acoustic features.

# Audio preprocess setting.
highpass_cutoff: 70 # Cut-off-frequency for low-cut-filter.
center: false # Pad the extracted sample to the center of the frame

# Mel-spectrogram extraction setting.
n_mels: 80
hop_length: 256 # Hop size.
win_size: 1024 # Window length.
n_fft: 1024
window: hann # Window function.
fmin: 0 # Minimum frequency in mel basis calculation.
fmax: 8000 # Maximum frequency in mel basis calculation.
clip_val: 1e-5

# Praat settings
# Use fft_size or win_length of Mel-spectrogram extraction setting
minf0: 75.0 # Minimum F0 value.
maxf0: 600 # Maximum F0 value.
thresholds: 0.6

# Burg
n_formant: 5
search_fo_min: 2500 # 5,000 Hz for femail, 5,500 Hz for mail
search_fo_max: 6000 # 5,000 Hz for femail, 5,500 Hz for mail
search_step: 50
fo_win_size: 600
pre_enphasis: 50
